spring:
  application:
    name: global-station-actor-service
  datasource:
    url: jdbc:mysql://localhost:3306/global_station_db
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true



server:
  port: 8400