spring:
  application:
    name: global-station-admin-service
  datasource:
    url: jdbc:mysql://localhost:3306/global_station_db
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true


server:
  port: 8100

#logging:
#  level:
#    root: INFO
#    org.springframework.boot.autoconfigure: DEBUG
#    org.springframework.beans: DEBUG
#    org.springframework.web: DEBUG
